### ISSUE TITLE
Design name tag template

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/convenings#10]
For events that do not require a lanyard, we need a name tag template. The design could be a condensed version of the front of the lanyard #1 and should include: 
- mozilla wordmark
- hackable space for name
- hackable space for a secondary piece of info (e.g. twitter handle or organization)
- if space allows, hackable space for icebreaker text (e.g. I'm good at____.) See @Melechuga's comment on this in #1.

Ideally, these could be printed on sticker paper on a standard office printer.

**Comment by edrushka** [comment]
The dimensions of the Avery self-adhesive name badge are:
North America: 2-1/3" x 3-3/8" (59mm x 86mm)
UK: slightly smaller at 50mm x 80mm

**Comment by edrushka** [comment]
@Melechuga could you please provide the text for the icebreaker you'd like to use on the name tags. Minimal wordcount, please!

**Comment by edrushka** [comment]
@Melechuga please take a look at this redpen and let us know what designs you like. I don't think there's room for an icebreaker on this size asset (it would work on the lanyard) so we've removed that element. https://redpen.io/p/byd09d21d9461d13c7

**Comment by edrushka** [comment]
@omnignorant @LindseyFrost @Saallen @arlissc we're making this name tag for Melissa's upcoming Open Web Fellow's meetup, but afterwards we hope to us it as an evergreen asset that any team can hack for their own use. Would love your feedback on the designs in this redpen -- specifically flags on what elements would (or would not) work for your community: https://redpen.io/p/byd09d21d9461d13c7

Goals:
- can be printed cheaply (ideally on an office printer)
- easy to hack. won't need a designer to adjust it for your event
- can be used when size/budget of convening doesn't warrant a lanyard
- has an element of Mozilla branding, but enough flexibility to work for all teams

**Comment by Melechuga** [comment]
I love the colors and designs! Thanks for sharing this. My comments are:
- We probably shouldn't use the megaphone logo, as that's being phased out (and is no longer on the website). Can we just use the regular Mozilla wordmark?
- For the purposes of this Meet Up, I'd prefer not having "Open Web Fellows" on the sticker; we are inviting many people in the space, and the focus is on Emerging Leaders. If you'd like to use "Emerging Leaders" in place of "OWF" that would be great. Alternatively, just keep it as "Mozilla" branded.

**Comment by edrushka** [comment]
Here's a redpen with no logos and "open web fellows" replaced with "emerging leaders" https://redpen.io/hn58ffd2fe712d1c85

**Comment by Melechuga** [comment]
Thanks @edrushka + @sabrinang ! I'm really loving these. After a call with the various attendees this morning, would it be possible to add a gray twitterbird + @ at the bottom (or just the bird) so people can include their handles?

**Comment by sabrinang** [comment]
Pattern and red name labels exported here (2-1/3"x3-3/8" (59x86mm) for Avery 5395 labels): https://drive.google.com/open?id=0B4Q8pzCpDS_eRzJyT2l3M1ZjMnM

**Comment by sabrinang** [comment]
@Melechuga ^ Let me know if you need me to make any adjustments to these labels?

**Comment by Melechuga** [comment]
Thanks @sabrinang! Is it possible to get the design for one that says "Emerging Leaders"? I'd be happy to try and see if the red one with the geometric pattern on the left works when printed (but if you don't mind giving me both solid red and geometric, that would be awesome).

**Comment by sabrinang** [comment]
Updated the folder to include side layout design with "Emerging Leaders" here: https://drive.google.com/open?id=0B4Q8pzCpDS_eRzJyT2l3M1ZjMnM

**Comment by sabrinang** [comment]
Thanks @Melechuga for some great feedback so far. I'll recap on the issue here!

It was helpful that Melissa photographed images so I can help troubleshoot. It will be useful to supply organizers with some print tips as we figured that printing settings differ and we can help suggest to print at original size (vs. some defaults that print to fit etc.) that could help in alignment issues. 

She shared some findings that the Mozilla SF + MTV offices give nametags to visitors that are "Mozilla is my dinosaur" themed:
![name-tag_example](https://cloud.githubusercontent.com/assets/2492510/14124621/4c0a8bbc-f5bb-11e5-9358-c7d45cceceea.png)
Melissa also pointed out to consider the paper finishes to use. We can try glossy, shiny labels vs. regular paper ones that may soak up marker or bleed ink easily due its porous qualities.

Also, we need to consider designing for in-house/office printer printing and may to adjust some of the unified colours (to darker shades) so the colours have higher contrast when printed. If you have any more photos or feedback from your event please let us know this has been insightful :)

**Comment by Melechuga** [comment]
We didn't take any pictures at the event, as we didn't ask ahead of time if that would be ok -- we have some people in sensitive situations. 

This made me realize that sticker nametags that often fall off, or are covered by hair, may not be as effective as multi-colored lanyards to show whether or not someone wants their photo taken. Also, because the stickers are placed high up on the torso, any photo would most likely include their name and Twitter handle. 

It would be interesting to see how we could include the "no photo" option into sticker nametags -- perhaps its as easy as different colored ones.

**Comment by sabrinang** [comment]
This is great feedback Melissa! I'll file another issue for a photo consent poster too.

**Comment by arlissc** [comment]
@sabrinang - we (Mozilla Science Lab) would love to use your name tag designs for our global sprint (June 02-03).  Wondering where you are with a re-useable template that we can use ? thx

**Comment by sabrinang** [comment]
@arlissc Yes, I made some "Global Sprint" iterations on the redpen: https://redpen.io/p/byd09d21d9461d13c7

Let me know if you have any preferences for copy ("Global Sprint"), colours and layout.

**Comment by edrushka** [comment]
@arlissc please let us know what copy and colours you'd like.

**Comment by edrushka** [comment]
This heartbeat, we'll devise a photo consent solution for these name tags.

**Comment by arlissc** [comment]
@edrushka @sabrinang - will discuss at our check-in meeting today and send preferences shortly after

**Comment by sabrinang** [comment]
Thank you for your feedback on the redpen and I have updated the tag (removed @ symbol and using the version without science logo to keep it visually less busy against the bg). Iterations on the redpen: https://redpen.io/p/byd09d21d9461d13c7

![convenings_name-tag_global-sprint-science_ideas-preview](https://cloud.githubusercontent.com/assets/2492510/14727336/ac950068-07de-11e6-9069-3eebaaf401bb.png)

The science site update is in the works and I checked out the palette https://github.com/mozilla/science.mozilla.org/issues/139#issuecomment-208605198

The 3 name tag sheets are on google drive here: https://drive.google.com/folderview?id=0B4Q8pzCpDS_eai1wM2YtVW1sVjQ&usp=sharing

Exported to fit [Avery 5395 Adhesive Name Badges](http://www.avery.com/avery/en_us/Products/Name-Badges/Name-Badges/Self-Adhesive-Removable-Name-Badge-Labels-PVC-Free_05395.htm)

I am unsure which specific colour reflects science/global sprint the best but please let me know if there are any changes or dimensions you need these to be exported in.

**Comment by edrushka** [comment]
cc @auremoser
