### ISSUE TITLE
Build a community Stepping stones doc

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/convenings#4]
I want to build a community Stepping Stones document that will record the following and highlight the paths
- Name
- Home community
- Initial pt of engagement
- Personal relationship with mozilla defined as
- Current project
- Future touch pts of the mentorship
- 

@edrushka any other field headings you think we need? Was thinking of using Harry  and his last year as my first example

**Comment by edrushka** [comment]
The only other thing I can think of is age, simply because bringing minors to events outside of their city will likely require chaperones.

Also, we should be sure to lock this doc up tight since it will have a lot of PII.

Let me know when you're ready and I'll import my notes from HCB (or I can just email you my text doc).

**Comment by edrushka** [comment]
Update: this doc has been started [here](https://docs.google.com/spreadsheets/d/1IStTtFoJFNZAxwWexXwt0pXNDp12W_tFH8Lnw5zC-yc/edit#gid=0) but you must request access from Sarah or I as it contains Personally identifiable Information.

**Comment by chrislarry33** [comment]
Can you add me

And hi!

**Comment by Saallen** [comment]
@edrushka thanks for adding in your notes too- I still feel I am missing a field- esp when I think of the converstations we had with the HCB16 (still happening :))
New field heading : Standout personal statements?

**Comment by edrushka** [comment]
Closing this ticket as the document has been created and will be update on an ongoing basis.
